apache/dolphinscheduler-sdk-python

- .asf.yaml
- .github/mergeable.yml
- README.md
Enhance our CI by adding mergeable and enable github issue
> [ci] Add mergeable and enable github issue

- .github/codecov.yml
- .github/workflows/ci.yaml
- .gitignore
- README.md
- tox.ini
* Add coverage for PR and badge. fix: https://github.com/apache/dolphinscheduler/issues/8256
* Add schedule job to check upstream apache/dolphinscheduler
  code work or not
* Fix deadlink
> [chore] Improve CI and fix deadlink

- .github/workflows/ci.yaml
- docs/source/concept.rst
- docs/source/config.rst
- src/pydolphinscheduler/configuration.py
- src/pydolphinscheduler/core/process_definition.py
- src/pydolphinscheduler/default_config.yaml
- src/pydolphinscheduler/java_gateway.py
- tests/core/test_process_definition.py
- tests/utils/test_yaml_parser.py
Up to now, we can only submit workflow with parallel mode. this patch give users ability specific execute type to workflow
> [feat] Add execute type to workflow

- README.md
- docs/source/index.rst
> [doc] Add history and version compatibility

- .github/workflows/ci.yaml
- CONTRIBUTING.md
- README.md
- RELEASE.md
* integrate test will trigger when have specific flag in message
* Change some contributing docs
* Add release detail docs
> [chore] Change integrate test behavior and add some doc

- src/pydolphinscheduler/java_gateway.py
- tests/integration/test_java_gateway.py
Avoid warnings unmatch in dev version code
> [impv] Do not warnings in dev version

- docs/source/concept.rst
- docs/source/howto/index.rst
- docs/source/howto/multi-resources.rst
- src/pydolphinscheduler/core/task.py
- src/pydolphinscheduler/core/workflow.py
- src/pydolphinscheduler/examples/multi_resources_example.py
- src/pydolphinscheduler/models/tenant.py
- tests/integration/test_resources.py
- tests/testing/constants.py
* Fix resource upload function
* And some documentation about how to use resource uploading
[run-it]
> [fix] Resource upload and add document

- .github/workflows/ci.yaml
ref: https://github.com/actions/setup-python/issues/162#issuecomment-1325307787
> [chore] Fix ubuntu-latest can not setup python in github action

- src/pydolphinscheduler/core/task.py
- src/pydolphinscheduler/core/workflow.py
- tests/core/test_task.py
> [impv] Add option param for workflow and task

- tests/tasks/test_condition.py
- tests/tasks/test_datax.py
- tests/tasks/test_dependent.py
- tests/tasks/test_dvc.py
- tests/tasks/test_flink.py
- tests/tasks/test_http.py
- tests/tasks/test_kubernetes.py
- tests/tasks/test_map_reduce.py
- tests/tasks/test_mlflow.py
- tests/tasks/test_openmldb.py
- tests/tasks/test_procedure.py
- tests/tasks/test_python.py
- tests/tasks/test_pytorch.py
- tests/tasks/test_sagemaker.py
- tests/tasks/test_shell.py
- tests/tasks/test_spark.py
- tests/tasks/test_sql.py
- tests/tasks/test_sub_workflow.py
- tests/tasks/test_switch.py
> [Test] Optimize the test cases in the task plugin

- examples/yaml_define/MoreConfiguration.yaml
- src/pydolphinscheduler/constants.py
- src/pydolphinscheduler/core/task.py
- tests/core/test_engine.py
- tests/core/test_task.py
> [Feat] Add task caching mechanism to improve the running speed of repetitive tasks

- .github/workflows/ci.yaml
- RELEASE.md
- docs/source/conf.py
- setup.cfg
- setup.py
- src/pydolphinscheduler/__init__.py
Use setup.cfg to config dist package. the benefit is we can use `attr` and `file` setup.cfg for convenient setting
> feat: Use setup.cfg for dist package

- docs/source/index.rst
> doc: Change doc base on Debra Chen advices

- .gitignore
- RELEASE.md
- setup.py
After this patch merge, we can create apache release resource by `python setup.py sdist`, it will create tarball and sign it for us
> feat: Add convenient method to create apache release resource

- src/pydolphinscheduler/tasks/python.py
> fix: Solve task python dependency with stmdency

- RELEASE.md
> doc: Correct release document

- RELEASE.md
doc: Add backward compatibility check before release
> doc: Add backward compatibility check before release

- .dlc.json
- src/pydolphinscheduler/configuration.py
> fix: Correct the bad env name of users tenant

- README.md
- docs/source/concept.rst
- docs/source/conf.py
> doc: correct crontab in schedule

- docs/source/concept.rst
> doc: Add how to config alert

- docs/source/concept.rst
- src/pydolphinscheduler/core/task.py
- tests/core/test_engine.py
- tests/core/test_task.py
```py
extract = Shell(
name="extract",
command="echo 'Some extract command here'",
task_group_id=1,
task_group_priority=123
)
```
fix: #106
> feat: Add task group to task class

- src/pydolphinscheduler/constants.py
- src/pydolphinscheduler/core/resource.py
- src/pydolphinscheduler/core/task.py
- tests/core/test_task.py
- tests/integration/test_resources.py
> Revert "[fix] Resource upload in dev branch

- .dlc.json
> fix: CI deadlink error

- .pre-commit-config.yaml
- .ruff.toml
- setup.cfg
- src/pydolphinscheduler/configuration.py
- src/pydolphinscheduler/core/mixin.py
- src/pydolphinscheduler/core/resource_plugin.py
- src/pydolphinscheduler/core/task.py
- src/pydolphinscheduler/core/yaml_workflow.py
- src/pydolphinscheduler/models/meta.py
- src/pydolphinscheduler/resources_plugin/base/bucket.py
- src/pydolphinscheduler/resources_plugin/base/git.py
- src/pydolphinscheduler/resources_plugin/gitlab.py
- src/pydolphinscheduler/resources_plugin/local.py
- src/pydolphinscheduler/utils/versions.py
- tests/core/test_yaml_workflow.py
- tests/testing/file.py
- tests/utils/test_default_config_yaml.py
- tests/utils/test_yaml_parser.py
> feat: introduce ruff for linter

- tests/integration/test_user.py
related change: https://github.com/apache/dolphinscheduler/pull/15254
[run-it]
> fix: Integration test error

- src/pydolphinscheduler/examples/task_datax_example.py
- src/pydolphinscheduler/tasks/datax.py
> impv: Add some docs for datax

- src/pydolphinscheduler/examples/tutorial.py
fix: https://github.com/apache/dolphinscheduler/issues/8955
> added multiple lines shell example

- .github/workflows/ci.yaml
- README.md
- docs/source/start.rst
- tests/integration/conftest.py
- tests/integration/test_project.py
- tests/integration/test_resources.py
- tests/integration/test_tenant.py
- tests/integration/test_user.py
- tests/testing/docker_wrapper.py
> Fix ci lint error

- .github/workflows/ci.yaml
> ci: fix codecov/codecov-action not work at macos-13

- docs/source/start.rst
Add the note for users to change and update pyds token.
> [Improvement][Doc] Add the note for users to change and update pyds token

- .github/workflows/ci.yaml
- .ruff.toml
- CONTRIBUTING.md
- docs/source/start.rst
- setup.cfg
according to https://devguide.python.org/versions/
> Remove py 3.8 support

- .github/workflows/ci.yaml
- src/pydolphinscheduler/constants.py
- src/pydolphinscheduler/core/workflow.py
- src/pydolphinscheduler/java_gateway.py
- src/pydolphinscheduler/tasks/dependent.py
- src/pydolphinscheduler/tasks/sub_workflow.py
- tests/core/test_yaml_workflow.py
- tests/tasks/test_dependent.py
- tests/tasks/test_sub_workflow.py
> fix: adapt the latest java trigger worflow code
